## C Source Map Generator for CodeTracer — V2 (side-annotated)
##
## V2 design vs V1:
##
## V1 emitted real `#line N FX_K` preprocessor directives plus
## `#define FX_K "path"` lines into the generated C. After codegen
## finished, V1 text-parsed the C source to reconstruct the mappings.
## The .c file shipped to gcc retained the `#line` directives, which
## gcc consumed and propagated into DWARF — making the generated C
## unsteppable in gdb/lldb (every C statement appeared "at" a Nim
## source line).
##
## V2 uses an out-of-band side channel:
##   - At every emit site that previously called `genCLineDir`, the
##     compiler now records a side annotation `(info, endInfo)` and
##     writes an opaque marker `"\14@CTSM\31<index>\15"` into the
##     same section buffer (SO + '@CTSM' + US + decimal index + SI).
##     The marker uses ASCII control bytes so it cannot appear in
##     user code and is trivially scanned for.
##   - After `genModule` concatenates all sections into the final
##     `code: string`, this module scans `code` once: for each marker
##     it computes the absolute (line, col) of the *next* byte, looks
##     up the side annotation by index, and registers the mapping.
##   - The markers are then stripped from `code`. The .c file written
##     to disk contains zero `#line`, zero `#define FX_`, zero
##     CodeTracer-specific markup. DWARF generated by gcc therefore
##     references real C lines, not Nim lines.
##
## The JSON file (`ct_sourcemap_<module>`) keeps V1's overall shape so
## existing V1 readers that index `[0]`/`[1]` continue to work; V2
## extends each entry from `[cPathID, cLine]` to
## `[cPathID, cStartLine, cStartCol, cEndLine, cEndCol, nimStartCol, nimEndCol]`
## and adds `"version": 2` at the top level.

import std/[os, strutils, tables, json]
when defined(nimPreviewSlimSystem):
  import std/syncio

import lineinfos, options, msgs

const
  ## Marker byte sequence injected into section buffers by
  ## `emitSourcemapMarker`. Format: SO '@CTSM' US <decimal-index> SI
  ##  - SO (\14) and SI (\15) are distinct from the
  ##    `postprocessDirStart` (\1) / `postprocessDirEnd` (\23) pair
  ##    used by `postprocessCode` for `nimln` directives, so the two
  ##    in-band systems don't collide.
  ##  - US (\31) separates fields.
  ctsmStart* = "\14@CTSM\31"
  ctsmEnd* = "\15"

type
  CSourcemapAnnotation* = tuple[
    info: TLineInfo,      # Nim file/line/col at the start of the range
    endInfo: TLineInfo    # Nim file/line/col at the end (== info for
                          # line-granular emits; differs for
                          # expression-level `emitRangeAt` sites)
  ]

  CSourcemapEntry* = tuple[
    cPathID: int,
    cStartLine, cStartCol: int,
    cEndLine, cEndCol: int,
    nimStartCol, nimEndCol: int
  ]

  CSourceMap* = ref object
    cSources*: Table[string, int]
    nimSources*: Table[string, int]
    mappings*: seq[TableRef[int, seq[seq[CSourcemapEntry]]]]
    ## For each Nim source (by pathID index), a table mapping Nim line
    ## numbers to groups of consecutive C line ranges.

proc newCSourceMap*(): CSourceMap =
  CSourceMap(
    nimSources: initTable[string, int](),
    cSources: initTable[string, int](),
    mappings: @[]
  )

proc renderMarker*(index: int): string =
  ## Returns the marker text to emit into a section buffer.
  ctsmStart & $index & ctsmEnd

proc parseMarker(s: string, start: int): tuple[index: int, endPos: int] =
  ## Parses a marker starting at `s[start]` (which must be SO / `\14`).
  ## Returns (annotation index, position just past the marker's SI).
  ## If parsing fails, returns (-1, start+1).
  let prefixLen = ctsmStart.len
  if start + prefixLen > s.len: return (-1, start + 1)
  for i in 0 ..< prefixLen:
    if s[start + i] != ctsmStart[i]: return (-1, start + 1)
  let endIdx = s.find(ctsmEnd, start + prefixLen)
  if endIdx == -1: return (-1, start + 1)
  let payload = s[start + prefixLen ..< endIdx]
  try:
    let idx = parseInt(payload)
    return (idx, endIdx + ctsmEnd.len)
  except ValueError:
    return (-1, start + 1)

proc stripMarkersAndCollect*(
    map: CSourceMap;
    code: string;
    annotations: seq[CSourcemapAnnotation];
    cfile: string;
    conf: ConfigRef): string =
  ## Walks `code`, computing (line, col) positions on the fly so each
  ## marker we encounter can be turned into a JSON mapping entry. The
  ## marker text itself is stripped from the returned string.
  ##
  ## Returned string is the cleaned C source ready to write to disk.
  if cfile notin map.cSources:
    map.cSources[cfile] = map.cSources.len
  let cPathID = map.cSources[cfile]

  result = newStringOfCap(code.len)
  var cLine = 1
  var cCol = 1
  var i = 0
  # Pending annotation whose start has been recorded but end is not
  # yet known (we close it when we hit the next marker on the same
  # Nim line, or at EOF).
  var pending: bool = false
  var pendingAnnIdx: int = -1
  var pendingStartCLine = 0
  var pendingStartCCol = 0
  # Group tracking: consecutive markers for the same Nim line share a
  # group (mirrors V1's `seq[seq[Line]]` shape).
  var lastNimPathIdx = -1
  var lastNimLine = -1

  proc closePending(annotations: seq[CSourcemapAnnotation];
                    map: CSourceMap;
                    cPathID: int;
                    cLine, cCol: int;
                    pendingAnnIdx: int;
                    pendingStartCLine, pendingStartCCol: int;
                    lastNimPathIdx, lastNimLine: var int) =
    if pendingAnnIdx < 0 or pendingAnnIdx >= annotations.len: return
    let ann = annotations[pendingAnnIdx]
    let nimFi = ann.info.fileIndex.int32
    if nimFi.int < 0: return
    let nimPath =
      try: toFullPath(conf, ann.info.fileIndex)
      except: ""
    if nimPath.len == 0: return
    if nimPath notin map.nimSources:
      map.nimSources[nimPath] = map.nimSources.len
      map.mappings.add(newTable[int, seq[seq[CSourcemapEntry]]]())
    let pathIdx = map.nimSources[nimPath]
    let nimLine = int(ann.info.line)
    if nimLine <= 0: return
    # Start a new group if we switched Nim source or Nim line.
    if pathIdx != lastNimPathIdx or nimLine != lastNimLine or
        nimLine notin map.mappings[pathIdx]:
      if nimLine notin map.mappings[pathIdx]:
        map.mappings[pathIdx][nimLine] = @[]
      map.mappings[pathIdx][nimLine].add(@[])
      lastNimPathIdx = pathIdx
      lastNimLine = nimLine
    let entry: CSourcemapEntry = (
      cPathID: cPathID,
      cStartLine: pendingStartCLine,
      cStartCol: pendingStartCCol,
      cEndLine: cLine,
      cEndCol: cCol,
      nimStartCol: int(ann.info.col),
      nimEndCol: int(ann.endInfo.col)
    )
    map.mappings[pathIdx][nimLine][^1].add(entry)

  while i < code.len:
    let ch = code[i]
    if ch == ctsmStart[0] and i + ctsmStart.len <= code.len and
        code[i ..< i + ctsmStart.len] == ctsmStart:
      # Marker boundary: close prior annotation, open new one.
      let (idx, nextPos) = parseMarker(code, i)
      if idx < 0:
        # Malformed; emit byte literally and advance one.
        result.add(ch)
        if ch == '\n':
          inc cLine
          cCol = 1
        else:
          inc cCol
        inc i
        continue
      if pending:
        closePending(annotations, map, cPathID, cLine, cCol,
                     pendingAnnIdx, pendingStartCLine, pendingStartCCol,
                     lastNimPathIdx, lastNimLine)
      pending = true
      pendingAnnIdx = idx
      pendingStartCLine = cLine
      pendingStartCCol = cCol
      i = nextPos
      continue
    # Regular byte: copy through and advance the (line, col) cursor.
    result.add(ch)
    if ch == '\n':
      inc cLine
      cCol = 1
    else:
      inc cCol
    inc i

  if pending:
    closePending(annotations, map, cPathID, cLine, cCol,
                 pendingAnnIdx, pendingStartCLine, pendingStartCCol,
                 lastNimPathIdx, lastNimLine)

proc serializeEntry(e: CSourcemapEntry): JsonNode =
  result = newJArray()
  result.add(%e.cPathID)
  result.add(%e.cStartLine)
  result.add(%e.cStartCol)
  result.add(%e.cEndLine)
  result.add(%e.cEndCol)
  result.add(%e.nimStartCol)
  result.add(%e.nimEndCol)

proc serializePathMap(pathMap: TableRef[int, seq[seq[CSourcemapEntry]]]): JsonNode =
  result = newJObject()
  for nimLine, groups in pathMap:
    var groupsJson = newJArray()
    for group in groups:
      var groupJson = newJArray()
      for entry in group:
        groupJson.add(serializeEntry(entry))
      groupsJson.add(groupJson)
    result[$nimLine] = groupsJson

proc serialize*(map: CSourceMap): string =
  var mappingsJson = newJArray()
  for pathMap in map.mappings:
    mappingsJson.add(serializePathMap(pathMap))
  let jsonNode = %*{
    "version": 2,
    "nimSources": %map.nimSources,
    "cSources": %map.cSources,
    "mappings": mappingsJson
  }
  return pretty(jsonNode)

proc writeSourceMap*(map: CSourceMap, outDir: string, outFileName: string) =
  let path = outDir / "ct_sourcemap_" & outFileName
  writeFile(path, map.serialize())
